name: flet_quill
description: Flet FletQuill control
repository: https://github.com/MyGithubAccount/flet-quill/src/flutter/flet_quill
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-quill

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter
  flutter_quill: ^11.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
